.github/workflows/reusable-terraform-management.yml

only require a token when allowApply is set.
attempts to fix
> Secret TF_API_TOKEN is required, but not provided while calling.
https://github.com/GeoNet/terraform-fastly/actions/runs/5341437186?pr=90

feat: update tf-api-token requirements

---

.github/workflows/reusable-container-image-promotion.yml
.github/workflows/reusable-container-image-scan.yml
.github/workflows/reusable-docker-build.yml
.github/workflows/reusable-presubmit-github-actions-workflow-validator.yml
.github/workflows/reusable-presubmit-readme-toc.yml

- these workflows don't need to rely on a go.mod in a repo
- pin mdtoc to a version

chore: use go stable for non-go workflows

---

.github/workflows/reusable-go-container-apps.yml

fix: syntax for default push value in go-container-apps

---

.github/workflows/reusable-go-apps.yml
.github/workflows/reusable-go-container-apps.yml
.github/workflows/reusable-go-test.yml

Will allow for adding of arbitrary commands to setup the test environment; for example
```
testSetup: |
sudo apt-get install -y lolcat
docker run -d -p 5432:5432 -e POSTGRES_PASSWORD=postgres postgres:15.5-alpine
```
intended for https://github.com/GeoNet/fdsn/pull/238

feat: add eval for test setup commands

---

.github/workflows/reusable-docker-build.yml

implement existing patterns for builds
intended for use in https://github.com/GeoNet/fdsn/pull/238 to use setup to copy the Dockerfile template and append the CMD statement per image.

feat: add setup for shell command before docker build

---

.github/workflows/reusable-docker-build.yml

The default value for the AWS session timeout was on the wrong parameter

fix: update reusable-docker-build default

---

.github/workflows/reusable-dockerfile-lint.yml

use comma separated list for Dockerfile discovery in output to lint step.
GitHub Actions doesn't handle too well to multi-line values.
tested in https://github.com/BobyMCbobs/sample-docker-monorepo/actions/runs/5606286054/jobs/10256292679#step:4:1

fix: dockerfile lint outputs

---

.github/workflows/reusable-policy-conformance.yml

if a .conform.yaml isn't found, write a default configuration to that local in the root of the repo

feat: add default config to policy-conformance

---

.github/workflows/reusable-go-container-apps.yml

copying is better than typing, sometimes

fix: typo with aws role duration seconds

---

.github/workflows/reusable-go-build-smoke-test.yml
.github/workflows/reusable-golangci-lint.yml

to do things like install external dependencies before running
intended to fix jobs related to https://github.com/GeoNet/4D-Ashfall/pull/33, such as go-build smoke test and golangci-lint

feat: add setup to go-build and golangci-lint

---

README.md

move Dockerfile lint back into workflows heading

fix: toc structure with dockerfile-lint

---

.github/workflows/reusable-policy-conformance.yml

Update the list to cover a wider range of messages that have been used across different repositories so far. To avoid overuse of the term `chore`
This update includes some that @ozym has been using already in `ac-tools`, `fix` and `ci`.

style: Update convention types list

---

.github/workflows/reusable-container-image-promotion.yml
.github/workflows/reusable-container-image-scan.yml
.github/workflows/reusable-docker-build.yml
.github/workflows/reusable-ko-build.yml

update when ready.
A new release was cut today without assets due to a error with the release lifecycle tools of go-containerregistry.
Use the latest known working version

fix: use fixed version of crane

---

README.md

github.ref works more reliably and has greater granuality

chore(docs): use ref instead of ref_name

---

.github/workflows/reusable-docker-build.yml

chore: make timeout-mins not required

---

.github/workflows/reusable-docker-build.yml
README.md

allows for downloading artifacts before docker build
best for use with 
https://github.com/GeoNet/Actions#copy-to-s3
TODO

feat: add download-artifact to docker-build

---

.github/workflows/reusable-golangci-lint.yml

This is needed as part of synching the local forked copy with its upstream master branch (would possibly handled by dependabot)

fix: pin golangci-lint to latest master hash

---

.github/workflows/reusable-golangci-lint.yml

This is to make the tests also fail when travis finds a problem, its using the latest version

fix: bump golangci-lint to 1.54.2

---

.github/workflows/reusable-go-container-apps.yml
.github/workflows/reusable-ko-build.yml
README.md

add a setup string input for executing arbitrary commands to initialise a build environment, through things like installing packages.
a Ko build is pretty much just Go build with extra container wrapper-y bits, so they inherit the same build properties from their host

feat: add setup input to ko-build

---

.github/workflows/reusable-bash-shellcheck.yml

the "uses: docker://" feature is broken in the org for some reason. just write it out as docker run for now. There's still some hidden GitHub magic which is given through "uses: docker://"
depends on: https://github.com/GeoNet/base-images/pull/84

fix: use expressed docker run for shell check

---

.github/workflows/reusable-ko-build.yml

missed this potential issue.
setup-go should be called before using `go list` to ensure that the expected version of Go is installed

chore: shuffle setup-go in ko-build

---

.github/workflows/reusable-docker-build.yml

build image in local docker before test and push.
prevents pulling image using existing tag which overrides image, instead uses locally built image in test.
fixes behaviour in: https://github.com/GeoNet/docker-gamit-base/actions/runs/6332302931/job/17198621752#step:21:12
also fixes order of setup and validate

chore: separate docker build and push for test

---

.github/workflows/presubmit-workflow-lint.yml
.github/workflows/reusable-container-image-scan.yml
.github/workflows/reusable-docker-build.yml
.github/workflows/reusable-presubmit-actions-workflow-require-commit-digest-vet.yml

yq is pre-installed in linux actions runner-images
and use base-images/binfmt instead of docker.io hosted image. depends on https://github.com/GeoNet/base-images/pull/110

chore: remove yq action

---

.github/workflows/reusable-policy-conformance.yml

disable spellcheck by using a non-existent locale _kiwi_.
We use kiwi English which is a combination between US and UK spelling.
Without modification, conform only supports either or.
it works! see: https://github.com/GeoNet/Actions/actions/runs/6488227007/job/17620216640?pr=206

chore: disable spellcheck in policy-conformance

---

.github/workflows/reusable-docker-build.yml
.github/workflows/reusable-ko-build.yml

some builds need base images from other repos and need to special auth

chore: remove ghcr auth override push gate for ko

---

.github/workflows/reusable-ko-build.yml
.github/workflows/test-reusable-ko-build.yml
go.mod

feat: add ko-build tests

---

.github/dependabot.yml

use an allowed commit prefix
attempts to resolve: https://github.com/GeoNet/base-images/pull/125
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#commit-message

chore: use dependabot semantic commit message

---

.github/dependabot.yml

currently the formatting doesn't meet conform standards
from the [docs](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#commit-message): ... This means that, for example, if you end the prefix with a whitespace, there will be no colon added ...

fix: make dependabot create conform compatible PR's

---

go.mod

Reference: https://github.com/GeoNet/tickets/issues/13645

chore: upgrade to go version 1.21

---

.github/workflows/reusable-go-apps.yml
.github/workflows/reusable-go-vet.yml
.github/workflows/reusable-govulncheck.yml

Reference: https://github.com/GeoNet/tickets/issues/15422
In doing the above ticket^, I have found the `reusable-go-apps` workflow not very reusable at all. This change will align it more closely with its name.
Tested here, works: https://github.com/GeoNet/4D-Ashfall/actions/runs/9120866234/job/25079049471

feat: allow setup for go-vet, govulncheck, and go-build

---

.github/actions/tagging/action.yml
README.md

Motivating ticket: https://github.com/GeoNet/tickets/issues/14398
This PR adds a composite action providing a consistent tag, or at least, consistent outputs to construct such a tag.
This should be suitable for use in the reusable workflows, as well as explicitly within users own workflow jobs.
Currently, the proposed format is commit sha-timestamp-build id...for example, `1da9c71-20240515111413-9094587538`
Points to consider are:
- order of fields
- need for timestamp (which was part of my original work to better ensure "uniqueness", but may not be required in presence of build id
- any other missing fields

feat: allow use of consistent container tagging

---

.github/workflows/reusable-goimports.yml

For goimports reusable workflow, ignore any directory named vendor. This allows edge cases where a repository has an embedded project, for example dapper inside fits.

feat: ignore any directory named vendor

---

.github/workflows/reusable-copy-to-s3.yml

Adds ability to copy a single file to or from s3.
See https://github.com/GeoNet/docker-bnc/actions/runs/9513165236 for new feature in action, as well as a test that the current `cp` still works as current

feat: add single file copy mode

---

.github/workflows/reusable-copy-to-s3.yml

Adds a default value of `3600` to `aws-role-duration-seconds`, making it consistent with defaults for the docker build, ko build, and go container build workflows.

feat: add default session time

---

.github/workflows/reusable-ko-build.yml

This uses the same mechanism as the docker build action to add tags to ko build actions

feat: add tags to reusable-ko-build

---

.github/workflows/reusable-docker-build.yml

This PR adds (by default) to `reusable-docker-build` an additional tag to a built image - a `deployment-tag` (see [`GeoNet/Actions/tagging`)](https://github.com/GeoNet/Actions?tab=readme-ov-file#tagging)
The full uri is exposed via access to the reusable workflows outputs, and via artifacts uploaded by the reusable workflow (see https://github.com/GeoNet/s3browser/actions/runs/9282066620/job/25539328908)
The PR I believe is non-breaking; all that happens is that an additional tag will be added to the image by default, which _shouldn't_ break anything. (I'll note if breaking changes are acceptable here, I'd like to rename the current `tags` input, to `additional-tags`, so you have `additional-tags` and `deployment-tag` as your inputs).
This PR should ultimately enable the updating of task …

feat: add immutable tag as a default

---

.github/workflows/reusable-aws-deploy.yml
README.md

This PR adds a new workflow allowing for CICD-based deployments.
Typically, services using this workflow would be configured in Terraform (see https://github.com/GeoNet/terraform-aws/pull/1151).
Re: deployment generally, I see this as an option, not the option. I think Terraform-based deployments / Terraform-tracked explicit deployment tags can co-exist with CICD-based deployments.

feat: adds ability to create new task revisions, and optionally deploy

---

.github/workflows/reusable-aws-deploy.yml

Tries to deploy EventBridge rule event if it's ECS deployment

fix: add missing deployment type rule

---

.github/workflows/reusable-policy-conformance.yml
README.md

Our conventional commits are all over the place. Everyone uses different commit types and there are too many types that overlap. This significantly reduces the usefulness of conventional commits.
This PR aims to address this by radically simplifying the conventional commits to use three types:
New stuff, features.
Fixing broken stuff, correcting stuff, small improvements etc.
Non-functional-change. Documentation, code comments, refactoring, style changes etc. Stuff that doesnt DO anything.
NFC changes are easy to review.
It's much easier to pick one of these three categories for your commits than picking between the 10 types we have now.
I've used this format in a previous job and it works well.

fix: simplify conventional commits

---

.github/workflows/reusable-aws-deploy.yml

Add deployment summary to build logs, useful for when AWS ParamStore not being used.
Example output:
```
Task revision created: arn:aws:ecs:ap-southeast-2:615890063537:task-definition/tf-dev-gloria-ng-rinex-igs-service:48
Image URI: 615890063537.dkr.ecr.ap-southeast-2.amazonaws.com/gloria-ng-worker:20240808073759-git35bfa39
```

feat: add deployment summary

---

.github/workflows/reusable-eslint.yml

fix: bump node version in reuseable-eslint

---

.github/workflows/reusable-go-test.yml
README.md

Optional behaviour, provided an s3 role and bucket name are provided.
Tried here successfully: https://github.com/GeoNet/geocodenz/actions/runs/10257082014/job/28377435623?pr=49

feat: allow go test results to upload to s3.

---

.github/workflows/reusable-go-test.yml
README.md

This reverts commit 209d96c097af2aea729f656a6735e88937a90e48. 
Was getting this error when using the action in go-reusable-app: exceed the limit on called workflow depth of 3

Revert "feat: allow go test results to upload to s3"

---

.github/workflows/reusable-copy-to-s3.yml
.github/workflows/reusable-docker-build.yml
.github/workflows/reusable-go-test.yml

This PR migrates reusable workflows from upload/download artifacts v3 to v4.
v4 represents breaking changes: https://github.blog/news-insights/product-news/get-started-with-v4-of-github-actions-artifacts/#compatibility
To summarise:
- no longer upload the same named artifact more than once (PR fix: uses `overwrite: true` to maintain current behaviour)
- can only use download v4 to access artifacts uploaded with v4 (from code search, appears to be no case of a workflow using v3 to download an artifact produced by the reusables)
This PR should maintain current behaviour, and not break any existing workflows.

fix: migrate to artifacts v4

---

.github/workflows/reusable-aws-deploy.yml

tested with `gloria` and `docker-gamit` workflows

nfc!: bump aws-actions/amazon-ecs* versions

---

.github/workflows/reusable-golangci-lint.yml

This is required to allow linting of go 1.23 code and tools. It temporarily sets the action to be non-fatal to allow the repo code to catch up. Once this has happened the ignore line will be removed.

feat: update the golangci-lint action

---

.github/workflows/reusable-eslint.yml

This is ensures only JavaScript files in the directory that the eslint config file is are linted.
**Tested in Tilde:**
**Current failing:** https://github.com/GeoNet/tilde/actions/runs/12818154802/job/35742988801
**Using this branch, passing:**
https://github.com/GeoNet/tilde/actions/runs/12819085053/job/35745995955
**Using this branch, failing because of linting error:**
https://github.com/GeoNet/tilde/actions/runs/12819161652/job/35746254649

fix: confine linting to directory where eslint config file is

---

.github/actions/copy-from-s3/action.yml
.github/actions/copy-to-s3/action.yml
.github/actions/validate-bucket-uri/action.yml
README.md

Adapted from reusable-copy-to-s3 workflow. Having it as a composite action should help address the workflow nesting limit that we see in some situations

feat: add composite action for copying to s3

---

.github/workflows/reusable-go-apps.yml
.github/workflows/reusable-go-test.yml
README.md

Optional behaviour, when an s3 role and bucket name are provided.
Second attempt at this: https://github.com/GeoNet/Actions/pull/307
Now using a composite action to upload to s3, to avoid workflow nest limits.

feat: allow go test results to upload to s3

---

.github/workflows/reusable-golangci-lint.yml

This should be merged after all the go repos have been upgraded to 1.23

feat: restore the golangci-lint to no longer be ignored

---

.github/workflows/reusable-terraform-management.yml

- move to use the supported version
- tested here: https://github.com/GeoNet/terraform-aws/pull/1439
- related to: https://github.com/actions/cache/discussions/1510

fix: update cache gh action version

---

go.mod

This file is no longer used with the prior removal of test files

nfc: delete unused go.mod file to remove confusion

---

.github/workflows/reusable-policy-conformance.yml
README.md

enabling our teams to update docs without having to use another less specific prefix

feat: add docs into the prefix set
