GeoNet/Actions

- .github/workflows/reusable-go-apps.yml
- .github/workflows/reusable-go-container-apps.yml
- .github/workflows/reusable-goimports.yml
- README.md
ensure goimports are in-order for each document
> feat: add goimports workflow to go apps workflows

- .github/workflows/reusable-container-image-promotion.yml
The _include_ keyword goes outside of the array, not inside.
> fix: update cip matrix json forming

- .github/workflows/reusable-copy-to-s3.yml
- README.md
adds a workflow for copying or syncing a folder to an S3 bucket.
requires an IAM role to assume.
> feat: add reusable copy to s3 workflow

- README.md
add the example of using copy-to-s3 with the _from_ direction to the docs
> chore: update docs for copy from s3

- .github/workflows/reusable-go-container-apps.yml
- .github/workflows/reusable-ko-build.yml
configure a job whether to push the images or not
> feat: add push input to ko and container apps

- .github/workflows/reusable-docker-build.yml
- README.md
add ability to push directly to ECR and skip ghcr.
> feat: add ECR support for reusable-docker-build

- .github/workflows/reusable-docker-build.yml
behaviour not as intended. 
```
if: ${{ inputs.thing }}
```
might mean _if the value exists_, instead of _if the value is true_; like with
```
if: ${{ inputs.thing == true }}
```
> chore: use exact syntax for push

- .github/workflows/reusable-go-apps.yml
- .github/workflows/reusable-go-container-apps.yml
Attempt to fix the following error
https://github.com/GeoNet/fdsn/actions/runs/5571769108
> fix: use string not bool for testSetup

- .github/workflows/markdown-lint.yml
- .github/workflows/reusable-markdown-lint.yml
- README.md
for use in docs, amongst others
> feat: add markdown lint

- .github/workflows/reusable-markdown-lint.yml
missed an error on start up for markdown lint
> chore: fix markdown lint

- .github/workflows/reusable-ko-build.yml
> Fix reusable ko build single equals

- .github/workflows/reusable-docker-build.yml
- README.md
it is multi-lined, not comma separated
> chore: fix docs on docker buildArgs

- .conform.yml
- .github/workflows/reusable-policy-conformance.yml
make it start!
it appears to work over here
https://github.com/BobyMCbobs/sample-ko-monorepo/actions/runs/5638873206/job/15273451971
> chore: use workaround for conform

- .github/workflows/reusable-go-container-apps.yml
- .github/workflows/reusable-ko-build.yml
- README.md
> feat: add ECR push for ko and go-container-apps

- .conform.yaml
require more context for a commit
> chore: add commit body requirement

- .conform.yaml
- .github/workflows/reusable-policy-conformance.yml
some of the team aren't fully set up just yet.
Revert soon
> chore: disable commit signing requirement for now

- .github/workflows/reusable-ko-build.yml
> fix: add missing ecr login to ko-build workflow

- .github/workflows/reusable-ko-build.yml
> fix: add missing crane to ko-build

- .github/workflows/reusable-container-image-promotion.yml
> fix: promotion registry override variables

- .github/workflows/reusable-container-image-promotion.yml
- .github/workflows/reusable-go-container-apps.yml
adds log into ECR for container image promotion
> feat: add AWS auth to container image promotion

- .github/workflows/reusable-container-image-promotion.yml
ensure auth'd before checking for image, then copy
> chore: move ecr auth before promote copy

- .github/workflows/reusable-policy-conformance.yml
- README.md
add some notes regarding conventional commits and links to docs
> chore(docs): add more links and notes for conform

- .github/workflows/reusable-go-container-apps.yml
enable or disable for more split out workflows
> feat: add switch for image promotion

- .github/workflows/reusable-docker-build.yml
shakemap takes 39 mins to build
> timeout configurable reusable-docker-build

- .github/workflows/reusable-docker-build.yml
> fix: set artifact vars to not required

- .github/workflows/reusable-container-image-promotion.yml
- .github/workflows/reusable-docker-build.yml
- .github/workflows/reusable-go-container-apps.yml
- .github/workflows/reusable-ko-build.yml
- README.md
add alternative fields to provide for username and password to authenticate with
Tested
> feat: add override auth for ghcr.io

- .github/workflows/reusable-go-apps.yml
- .github/workflows/reusable-go-container-apps.yml
- .github/workflows/reusable-go-test.yml
add input to pass extra args to `go test` command
> chore: add extra args param to go test workflow

- .github/workflows/reusable-container-image-promotion.yml
- .github/workflows/reusable-container-image-scan.yml
- .github/workflows/reusable-docker-build.yml
- README.md
> chore: remove quay.io/geonet references

- .github/workflows/reusable-docker-build.yml
- .github/workflows/reusable-ko-build.yml
this currently provides no value as the metadata isn't being used
> chore: add gate for signing images

- .github/workflows/reusable-go-build-smoke-test.yml
some builds are a bit more... unique.
intended for fixing
https://github.com/GeoNet/fits/actions/runs/5872795381/job/15924966274?pr=218#step:7:7
> feat: add working-directory to input for go build

- .github/workflows/reusable-go-container-apps.yml
> fix: remove requirement for image promotion

- .github/workflows/reusable-container-image-promotion.yml
- .github/workflows/reusable-go-apps.yml
- .github/workflows/reusable-go-container-apps.yml
run workflow on the web or cli
> fix: ensure workflows are able to be dispatched

- .github/workflows/reusable-container-image-promotion.yml
- .github/workflows/reusable-docker-build.yml
- .github/workflows/reusable-go-apps.yml
- .github/workflows/reusable-go-container-apps.yml
- .github/workflows/reusable-stale-submission.yml
- .github/workflows/reusable-terraform-management.yml
- .github/workflows/reusable-update-go-version.yml
- README.md
- add workflow types description
- add status to workflows in README.md
- update some workflows to be deprecated
- update order of inputs in workflows to have required first
- update inputs to ensure more are passed through
- remove update-go-version from go [container] apps workflows
- remove container-image-promotion from go [container] apps workflows
- remove lifecycle management from terraform workflow
replaces #162
> chore: tidy workflows and docs

- README.md
comment for layout of new workflow documentation
> feat: add README.md template example comment

- README.md
ensure that status is in commented template for workflows
> feat: add workflow status to template

- .github/workflows/reusable-ko-build.yml
default to using GeoNet static base image when using ko
> feat: use default GeoNet/base-images/static for ko

- README.md
- hack/update-actions-imports.sh
add script to force update of actions workflow imports along with docs
> feat: add update actions workflow imports and docs

- .github/workflows/reusable-go-test.yml
- README.md
> chore: ensure retention-days is set for all upload-artifacts

- README.md
touch up on information, grammar and formatting
> chore: improve docs for workflows

- .github/workflows/reusable-go-build-smoke-test.yml
- .github/workflows/reusable-ko-build.yml
the previous command works reliably but is more challenging to understand. the new command here is essentially three commands piped together.
> chore: tidy command for Go pkg main discovery

- .github/workflows/reusable-terraform-management.yml
attempts to resolve unable to validate Terraform
related: https://github.com/GeoNet/terraform-datadog/pull/147
> chore: add terraform init to tf management

- .github/workflows/reusable-github-actions-action-validator.yml
- README.md
validates GitHub Action (not reusable workflow)
> feat: add workflow to validate GitHub Action

- .github/workflows/reusable-docker-build.yml
- .github/workflows/reusable-ko-build.yml
- go.mod
- add test input for running
- add runs-on input for choosing the machine type to run the build job on
- add validation step to docker build
- add target to build specified stage to build in Docker build
- remove image signing gate
- remove go.mod
> chore: update container workflows

- .github/workflows/presubmit-workflow-lint.yml
- .github/workflows/reusable-container-image-scan.yml
- .github/workflows/reusable-copy-to-s3.yml
- .github/workflows/reusable-docker-build.yml
- .github/workflows/reusable-ko-build.yml
- .github/workflows/reusable-terraform-management.yml
> chore: update actions upstream versions 290923

- .github/workflows/reusable-docker-build.yml
- .github/workflows/reusable-presubmit-actions-workflow-require-commit-digest-vet.yml
- .github/workflows/test-reusable-docker-build.yml
- testdata/t0-basic/Dockerfile
- testdata/t1-use-test/Dockerfile
- testdata/t2-artifact-pull/Dockerfile
- testdata/t3-multi-arch/Dockerfile
- testdata/t6-auth-with-geonetci/Dockerfile
- testdata/t7-use-setup/Dockerfile
- testdata/t8-use-tags/Dockerfile
- testdata/t9-no-push/Dockerfile
ensure changes continue conformant behaviour.
this PR also fixes the error in _commit-digest-vet_, which fails in this PR
> feat: add reusable-docker-build workflow tests

- .github/workflows/reusable-docker-build.yml
Presence of ghcr override inputs is sufficient to allow login.
> feat: remove push constraint for ghcr override

- branch-protections.md
- hack/list-checks.sh
adds docs and script for branch protection
> feat: add branch protection list checks

- branch-protections.md
- hack/list-checks.sh
- add append to yaml in docs
- print tidier yaml
- remove unique matrix items for checks
> chore: update docs for branch protection checks

- .github/workflows/reusable-docker-build.yml
- .github/workflows/reusable-go-container-apps.yml
- .github/workflows/reusable-ko-build.yml
- .github/workflows/reusable-markdown-lint.yml
- README.md
update several docs and inputs
> chore: misc maintainance updates

- .github/workflows/reusable-docker-build.yml
- .github/workflows/reusable-ko-build.yml
- README.md
remove container image signing since it isn't being utilised
> chore: remove container image signing

- .github/workflows/reusable-go-container-apps.yml
- .github/workflows/reusable-ko-build.yml
- README.md
adds an input to specify the path to a .ko.yaml config file.
Requested by @ozym
> feat: add Ko config path input

- README.md
how to get started and producing the first table of contents
> feat: add table of contents usage comments

- .github/workflows/reusable-docker-build.yml
- .github/workflows/reusable-ko-build.yml
- .github/workflows/test-reusable-docker-build.yml
- add default tags of _latest_ and _git-SHA_ to ko-build
- add git-SHA to docker-build
> chore: add tags to ko build + sha to docker build

- .github/workflows/reusable-copy-to-s3.yml
- .github/workflows/reusable-docker-build.yml
- .github/workflows/reusable-ko-build.yml
old sha didn't resolve
also removed invalid config for download-artifact
> chore: update aws configure version

- .github/workflows/reusable-clean-containers.yml
- README.md
reusable cleanup script so we can manage private container storage usage
otherwise private container images may use all 50GB/months of our storage plan
https://github.com/GeoNet/tickets/issues/14184
> feat: implement cleanup script

- .github/workflows/presubmit-check-action-exists.yml
- hack/check-actions-exist.sh
check that external actions exist
> feat: add check actions exist workflow and script

- README.md
> chore: add missing upload-artifact in README

- .github/workflows/reusable-golangci-lint.yml
fixes faulty slice detection issue
https://github.com/securego/gosec/pull/1017
G602
> chore: update golangci version

- .github/workflows/sync-actions-forks.yml
- hack/update-forks.sh
reduce maintenance toil on the ops team
> feat: auto sync forked actions repos

- .github/workflows/reusable-docker-build.yml
Currently, can only configure test, or push. This adds test AND/OR push.
> feat: allow test and push

- .github/workflows/reusable-container-image-scan.yml
due to updated action
https://github.com/GeoNet/tickets/issues/15264
> Drop trivy command line flags

- .github/workflows/reusable-container-image-scan.yml
low moderate errors are not worth our time
> fix: hotfix ignore low errors
